version: "1.0"

services:
  db:
    image: mysql:8.0.33
    volumes:
      - .dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TaaVAI
      MYSQL_PASSWORD: root
    ports: 
      - 3307:3306

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  
    
    volumes:
      - .:/code
    depends_on:
      - db

    env_file: .env